kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manifestwork-editor-role-binding
subjects:
  - kind: ServiceAccount
    name: {{.Values.serviceAccount.name}}
    namespace: default # TODO change
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manifestwork-editor-role
